service: hello-world

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2
  profile: default
  environment:
    someVariable: value1
custom:
  webpackIncludeModules: true

functions:
  app:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline
  - serverless-plugin-typescript

