service: hello-world

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2
  profile: default
custom:
  webpackIncludeModules: true
  serverless-offline-sns:
    port: 4005

functions:
  app:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-webpack
  - serverless-offline
