service: hello-world

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2
  profile: default
custom:
  webpackIncludeModules: true
  serverless-offline-sns:
    port: 4005
    debug: true

functions:
  app:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  queue:
    handler: src/queue.test
    events:
      - sns: testQueue

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-offline-sns
