// flow-typed signature: 33dcf0a5079efed7dc27bf6fe52bb183
// flow-typed version: <<STUB>>/saml2-js_v^1.12.2/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'saml2-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'saml2-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'saml2-js/lib-js/saml2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'saml2-js/index' {
  declare module.exports: $Exports<'saml2-js'>;
}
declare module 'saml2-js/index.js' {
  declare module.exports: $Exports<'saml2-js'>;
}
declare module 'saml2-js/lib-js/saml2.js' {
  declare module.exports: $Exports<'saml2-js/lib-js/saml2'>;
}
