// flow-typed signature: f74bbbee9088518bd2e69a537aa7c91e
// flow-typed version: <<STUB>>/winston-aws-cloudwatch_v^1.6.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'winston-aws-cloudwatch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'winston-aws-cloudwatch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'winston-aws-cloudwatch/lib/cloudwatch-client' {
  declare module.exports: any;
}

declare module 'winston-aws-cloudwatch/lib/cloudwatch-event-formatter' {
  declare module.exports: any;
}

declare module 'winston-aws-cloudwatch/lib/index' {
  declare module.exports: any;
}

declare module 'winston-aws-cloudwatch/lib/log-item' {
  declare module.exports: any;
}

declare module 'winston-aws-cloudwatch/lib/queue' {
  declare module.exports: any;
}

declare module 'winston-aws-cloudwatch/lib/relay' {
  declare module.exports: any;
}

// Filename aliases
declare module 'winston-aws-cloudwatch/index' {
  declare module.exports: $Exports<'winston-aws-cloudwatch'>;
}
declare module 'winston-aws-cloudwatch/index.js' {
  declare module.exports: $Exports<'winston-aws-cloudwatch'>;
}
declare module 'winston-aws-cloudwatch/lib/cloudwatch-client.js' {
  declare module.exports: $Exports<'winston-aws-cloudwatch/lib/cloudwatch-client'>;
}
declare module 'winston-aws-cloudwatch/lib/cloudwatch-event-formatter.js' {
  declare module.exports: $Exports<'winston-aws-cloudwatch/lib/cloudwatch-event-formatter'>;
}
declare module 'winston-aws-cloudwatch/lib/index.js' {
  declare module.exports: $Exports<'winston-aws-cloudwatch/lib/index'>;
}
declare module 'winston-aws-cloudwatch/lib/log-item.js' {
  declare module.exports: $Exports<'winston-aws-cloudwatch/lib/log-item'>;
}
declare module 'winston-aws-cloudwatch/lib/queue.js' {
  declare module.exports: $Exports<'winston-aws-cloudwatch/lib/queue'>;
}
declare module 'winston-aws-cloudwatch/lib/relay.js' {
  declare module.exports: $Exports<'winston-aws-cloudwatch/lib/relay'>;
}
